## 10) Write a python program to scrape first 10 product details which include product name , price , Image URL from https://www.bewakoof.com/women-clothing.

In [1]:
from bs4 import BeautifulSoup
import requests
import lxml
import numpy as np
import pandas as pd

## used BeautifulSoup and Selenium

In [12]:
number_of_listing = int(input('Enter the number of listings needed : '))

from selenium import webdriver
PATH = 'C:\Program Files (x86)\chromedriver.exe'
url = 'https://www.bewakoof.com/women-clothing'
driver = webdriver.Chrome(PATH)
driver.get(url)

page = driver.page_source
soup = BeautifulSoup(page)
bewakoof = []
URL = []
count = 0
while  count != number_of_listing:
    for main_file in soup.find_all('div',class_="productCardDetail"):
            name = main_file.find('h3').text
            price = main_file.find('span',class_='discountedPriceText' ).text
            org_price = main_file.find('span',attrs={'class':'actualPriceText'}).text
            if (len(name))>0 or len(price)>0:
                bewakoof.append([name,price,org_price])
                count+=1
    
    for main_file in soup.find_all('div',class_="productImg"):
            url1 = main_file.find('img')['src']
            URL.append(url1)
            
df1 = pd.DataFrame(URL)              
df = pd.DataFrame(bewakoof,columns=['Name','Discounted Price','Actual Price'])
df['URL']=df1
df

Enter the number of listings needed : 10000

<ipython-input-12-60d3b049f8c1>:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(PATH)

,Name,Discounted Price,Actual Price,URL
0,Women's Purple Dressed Up Snoopy Boyfriend T-s...,₹ 299,999,https://images.bewakoof.com/t320/women-s-purpl...
1,Women's Black One with the Universe Boyfriend ...,₹ 299,999,https://images.bewakoof.com/t320/one-with-the-...
2,Women's Green Sleepy Head (DL) Boyfriend T-shirt,₹ 299,999,https://images.bewakoof.com/t320/sleepy-head-d...
3,Women's Purple Music Escape Boyfriend T-shirt,₹ 299,999,https://images.bewakoof.com/t320/music-escape-...
4,Women's Black Dressed Up Snoopy Boyfriend T-shirt,₹ 299,999,https://images.bewakoof.com/t320/women-s-black...
...,...,...,...,...
9995,Women's Black Good Times Garfield T-shirt,₹ 349,999,NaN
9996,Chibi Harry Boyfriend T-Shirt (HPL),₹ 399,549,NaN
9997,Women's Black I Was Born Genius Typography T-s...,₹ 299,999,NaN
9998,Chilled Out Green Boyfriend T-shirt,₹ 399,699,NaN
9999,Tweety Origami Half Sleeve T-Shirt (LTL),₹ 199,549,NaN